version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: drogueria_db
    environment:
      POSTGRES_DB: drogueria_bellavista
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "JUNIORDIAZ"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
